### ISSUE TITLE
Проблема удаления медиа и ссылок

### ISSUE THREAD

**Issue by momai** [TiraelSedai/ClubDoorman#8]
Привет! У тебя очень классный бот, я его несколько недель гоняю на трех телеграм-группах, никак не связанных с клубом. Мне нравится принцип его работы и логика, так же, отмечу, что комментарии оставляемые ботом в админском чате выше всяческих похвал - они не перегружены, язык простой и понятный. Мало кто может похвастаться сейчас, автоматизированной обратной связью в любом продукте.
Окей, мне правда хотелось похвалить, т.к. есть за что. А теперь к возникшим проблемам:
1) Почему-то все сообщения с картинками пересылаются в админский чат. Иногда бот  удаляет эти сообщения, иногда предлагает выбор мне. Касается это пользователей которые уже давно вступили в группу.
2) В целом тоже поведение, но при отправке ссылок.
3) Любое медиа отправленное от имени группы, так же отправляется в админский чат. В целом это не проблема и сделано явно для своих нужд, но хотелось бы иметь возможность параметризировать этот экшн.

Создается ощущение, что бот не очень понимает, кто новый юзер, а кто старый, если бота добавили в чат с множеством участников. Быть может это как-то фиксится?

**Comment by TiraelSedai** [comment]
Бот действительно не знает, какие пользователи "старички", а какие только зашли. Вариант доверять всем кто есть чате, в текущий момент я не расматриваю, как раз одна из причина создания бота - за неделю что в одном из чатов не работала капча, туда просочилась куча ботов и сидели ждали своего часа, спамили потихоньку.

В целом в бот апи нет метода "получить всех текущих участников чата", поэтому в лоб задача не решается. Можно использовать клиентский апи (т.е. работать как телеграм клиент), и от имени админа чата получить айдишники всех юзеров и добавить их в approved-users.txt

1. удаляет те где нашёл спам, не удаляет те где нет подписей?
2. считает ссылки спамом?
3. если от имени не привязанного канала, то это by design. то, что люди хотят анонимности (непонятно кто запостил) или порекламить свои каналы это здорово конечно, но зачем оно нам (владельцам чата) непонятно. поскольку Дуров не сделал галочку "запретить писать от имени канала", оно сейчас запрещает всем, опт-аут через DOORMAN_CHANNELS_AUTOBAN_DISABLE 1

**Comment by momai** [comment]
1. Да, похоже на правду. Посмотрел на админ-чат, похоже так и есть
2. Считает ссылку спамом, но удаляет не всегда. Пока причины не понял.
3. С сообщениями от админки понял. Но это вообще ерунда, мне скорее интересна была причина такого решения. Это никак не влияет на работу и удобство пользования.

approved-users.txt - кажется это то что нужно. 

Тогда, на основе диалога, предварительно могу предложить фичу - добавить команду на добавление юзера в approved-users.
К примеру, я вижу что бот тригерится на участника которого я знаю. Реплаем добавляю его через команду /approve 

И бот, в активном чате легко, так скажем, "дообучится" и не будет  срабатывать на старожилах.

**Comment by momai** [comment]
https://github.com/TiraelSedai/ClubDoorman/pull/11
